context:
  version: 0.1.0
  python_min: "3.11"

package:
  name: logic1
  version: ${{ version }}

source:
  url: https://github.com/logic1-eu/logic1/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7149ce98cc9381da14de26f871c00f14fef12d0b3e482bef4c555ccfe8cc558d

build:
  number: 0
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=${{ python_min }},<3.12
    - more-itertools
    - pyeda
    - sage
    - typing-extensions

tests:
  - python:
      imports:
        - logic1
      pip_check: false
  - script:
      - python -m doctest -o NORMALIZE_WHITESPACE logic1/theories/Sets/test_qe.txt
    files:
      source:
        - logic1/theories/Sets/test_qe.txt
    requirements:
      run:
        - python ${{ python_min }}

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Interpreted first-order logic in Python
  homepage: https://docs.logic1.eu/
  documentation: https://docs.logic1.eu/
  description: |
    First-order logic recursively builds terms from variables and a specified set of function symbols with specified arities, which includes constant symbols with arity zero. Next, atomic formulas are built from terms and a specified set of relation symbols with specified arities. Finally, first-order formulas are recursively built from atomic formulas and a fixed set of logical operators.

    Logic1 focuses on interpreted first-order logic, where the above-mentioned function and relation symbols have implicit semantics, which is not explicitly expressed via axioms within the logical framework. Typical applications include algebraic decision procedures and, more generally, quantifier elimination procedures, e.g., over the real numbers.
  repository: https://github.com/logic1-eu/logic1

extra:
  recipe-maintainers:
    - lorenzleutgeb
    - thomas-sturm
